service: shopping-assistant

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  environment:
    AWS_S3_BUCKET: my-shopping-assistant-receipts
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
        - s3:*
      Resource: "*"

functions:
  createShoppingList:
    handler: handler.createShoppingListHandler
    events:
      - http:
          path: lists
          method: post
          cors: true

  getShoppingList:
    handler: handler.getShoppingListHandler
    events:
      - http:
          path: lists/{listId}
          method: get
          cors: true

  addItemToList:
    handler: handler.addItemToListHandler
    events:
      - http:
          path: lists/{listId}/items
          method: post
          cors: true

  removeItemFromList:
    handler: handler.removeItemFromListHandler
    events:
      - http:
          path: lists/{listId}/items/{itemId}
          method: delete
          cors: true

  addUserToList:
    handler: handler.addUserToListHandler
    events:
      - http:
          path: lists/{listId}/users
          method: post
          cors: true

  removeUserFromList:
    handler: handler.removeUserFromListHandler
    events:
      - http:
          path: lists/{listId}/users/{userId}
          method: delete
          cors: true

  markItemAsPurchased:
    handler: handler.markItemAsPurchasedHandler
    events:
      - http:
          path: lists/{listId}/items/{itemId}/purchase
          method: put
          cors: true

  deleteShoppingList:
    handler: handler.deleteShoppingListHandler
    events:
      - http:
          path: lists/{listId}
          method: delete
          cors: true

  generateReceiptUploadURL:
    handler: handler.generateReceiptUploadURLHandler
    events:
      - http:
          path: receipts/upload
          method: post
          cors: true